# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "pg-data:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
      PGADMIN_LISTEN_ADDRESS: 127.0.0.1

  admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yaj
      PGADMIN_DEFAULT_PASSWORD: yaj


volumes:
  pg-data: